version: '3.8'

services:
  postgres:
    image: postgres:14.9
    container_name: postgres-order-service
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: order
      POSTGRES_PASSWORD: orderservice
      POSTGRES_DB: order
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-schema-install:/docker-entrypoint-initdb.d

volumes:
  postgres-data: