spring:
  sql:
    init:
      mode: always
  application:
    name: order-service
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    hikari:
      schema: PUBLIC
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
  liquibase:
    change-log: classpath:/db/changelog/liquibase.xml
    enabled: false
